server:
  port: 8070

resilience4j:
  circuitbreaker:
    instances:
      external-user-validation:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 1
  retry:
    instances:
      external-user-validation:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - com.trevizan.javacoreplayground.exception.ExternalServiceException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
